### ISSUE TITLE
Typo in molAdd.py line 53

### ISSUE THREAD

**Issue by mrjoposranchik** [QijingZheng/pyband#14]
Should be "axis" instead of "exis" in molAdd.py line 53 :) 

Otherwise
Traceback (most recent call last):
  File "../molAdd.py", line 135, in <module>
    add_mol(sys.argv[1:])
  File "../molAdd.py", line 54, in add_mol
    new.center(vacuum=arg.vacuum / 2., axis=axis)
UnboundLocalError: local variable 'axis' referenced before assignment

**Comment by QijingZheng** [comment]
Hi mrjoposranchik

Thank you! I have changed it.

Best
Qijing
