### ISSUE TITLE
pyband problems

### ISSUE THREAD

**Issue by sky-lyan** [QijingZheng/pyband#21]
Dear Dr.Zheng
I got the following problems:
Do you have any idea for that
Thank you very much!
Traceback (most recent call last):
  File "./pyband", line 690, in <module>
    call(['feh', '-xdF', opts.bandimage])
  File "/home-gk/soft/packagedir/anaconda3/install/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home-gk/soft/packagedir/anaconda3/install/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home-gk/soft/packagedir/anaconda3/install/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'feh': 'feh'

**Comment by mahdi-ghorbani-asl** [comment]
Dear Dr. Zheng,
Thank you for the nice code!
I got an error when I used  ./pyband:

Traceback (most recent call last):
  File "./pyband", line 689, in <module>
    call(['feh', '-xdF', opts.bandimage])
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I appreciate it if you can give some advice

**Comment by Ionizing** [comment]
@sky-lyan @mahdi-ghorbani-asl 

That means your environment doesn't have an executable or function named `feh`. 

- Just add `-q` option to make it work quietly and the error will go away, the plot will be saved  as `dos.png`;
- Or you can install `feh` on your machine to let it show the plot immediately if you like.
