### ISSUE TITLE
Distorted band structure for HSE06 functional

### ISSUE THREAD

**Issue by nirjha008** [QijingZheng/pyband#27]
Dear Dr. Zheng,
Firstly thank you very much for this wonderful tool. I've been using this without any problem for PBE functionals. But recently I started HSE06 and since I'm getting this type of distorted bad structure. It is not wrong or anything, It's just the distance from gamma to k point is too much and it looks distorted. Any idea how to fix this or do I need to add something for HSE06?
Thank you very much.

![band](https://user-images.githubusercontent.com/104714131/204775768-8436f96e-c6d3-4fe6-a725-dd06e3d26808.png)

**Comment by QijingZheng** [comment]
Hi

Please try to pass "--hse" to pyband. See 'pyband --help' for more options.

Best
Qijing

**Comment by nirjha008** [comment]
Thank you very much for your reply .
Now I'm getting correct band structure, but after several trial I can not get the high symmetry points label correct. Probably I am setting the nseg-- incorrect. Can you kindly instruct how to set them?  There are total 68 non weighted KPOINTS,  segmented as Γ to M 25KPOINTS , M to K 14KPOINTS and K to Γ 29KPOINTS.  

The KPOINTS file - 
0.040   9   9   1   12  0.040   68    3   25   14   29           # Parameters to Generate KPOINTS (Do NOT Edit This Line)
    80
Reciprocal lattice
    0.00000000000000    0.00000000000000    0.00000000000000     1
    0.11111111111111    0.00000000000000    0.00000000000000     6
    0.22222222222222    0.00000000000000    0.00000000000000     6
    0.33333333333333    0.00000000000000    0.00000000000000     6
    0.44444444444444    0.00000000000000    0.00000000000000     6
    0.11111111111111    0.11111111111111    0.00000000000000     6
    0.22222222222222    0.11111111111111    0.00000000000000    12
    0.33333333333333    0.11111111111111    0.00000000000000    12
    0.44444444444444    0.11111111111111    0.00000000000000     6
    0.22222222222222    0.22222222222222    0.00000000000000     6
    0.33333333333333    0.22222222222222    0.00000000000000    12  
    0.33333333333333    0.33333333333333    0.00000000000000     2   K
    0.00000000000000    0.00000000000000    0.00000000000000     0   Γ
    0.02083333333333    0.00000000000000    0.00000000000000     0
    0.04166666666667    0.00000000000000    0.00000000000000     0
    0.06250000000000    0.00000000000000    0.00000000000000     0
    0.08333333333333    0.00000000000000    0.00000000000000     0
    0.10416666666667    0.00000000000000    0.00000000000000     0
    0.12500000000000    0.00000000000000    0.00000000000000     0
    0.14583333333333    0.00000000000000    0.00000000000000     0
    0.16666666666667    0.00000000000000    0.00000000000000     0
    0.18750000000000    0.00000000000000    0.00000000000000     0
    0.20833333333333    0.00000000000000    0.00000000000000     0
    0.22916666666667    0.00000000000000    0.00000000000000     0
    0.25000000000000    0.00000000000000    0.00000000000000     0
    0.27083333333333    0.00000000000000    0.00000000000000     0
    0.29166666666667    0.00000000000000    0.00000000000000     0
    0.31250000000000    0.00000000000000    0.00000000000000     0
    0.33333333333333    0.00000000000000    0.00000000000000     0
    0.35416666666667    0.00000000000000    0.00000000000000     0
    0.37500000000000    0.00000000000000    0.00000000000000     0
    0.39583333333333    0.00000000000000    0.00000000000000     0
    0.41666666666667    0.00000000000000    0.00000000000000     0
    0.43750000000000    0.00000000000000    0.00000000000000     0
    0.45833333333333    0.00000000000000    0.00000000000000     0
    0.47916666666667    0.00000000000000    0.00000000000000     0
    0.50000000000000    0.00000000000000    0.00000000000000     0  M
    0.50000000000000    0.00000000000000    0.00000000000000     0  M
    0.48717948717692    0.02564102563846    0.00000000000000     0
    0.47435897435385    0.05128205127692    0.00000000000000     0
    0.46153846153077    0.07692307691538    0.00000000000000     0
    0.44871794870769    0.10256410255385    0.00000000000000     0
    0.43589743588462    0.12820512819231    0.00000000000000     0
    0.42307692306154    0.15384615383077    0.00000000000000     0
    0.41025641023846    0.17948717946923    0.00000000000000     0
    0.39743589741538    0.20512820510769    0.00000000000000     0
    0.38461538459231    0.23076923074615    0.00000000000000     0
    0.37179487176923    0.25641025638462    0.00000000000000     0
    0.35897435894615    0.28205128202308    0.00000000000000     0
    0.34615384612308    0.30769230766154    0.00000000000000     0
    0.33333333330000    0.33333333330000    0.00000000000000     0 k
    0.33333333330000    0.33333333330000    0.00000000000000     0
    0.32142857139643    0.32142857139643    0.00000000000000     0
    0.30952380949286    0.30952380949286    0.00000000000000     0
    0.29761904758929    0.29761904758929    0.00000000000000     0
    0.28571428568571    0.28571428568571    0.00000000000000     0
    0.27380952378214    0.27380952378214    0.00000000000000     0
    0.26190476187857    0.26190476187857    0.00000000000000     0
    0.24999999997500    0.24999999997500    0.00000000000000     0
    0.23809523807143    0.23809523807143    0.00000000000000     0
    0.22619047616786    0.22619047616786    0.00000000000000     0
    0.21428571426429    0.21428571426429    0.00000000000000     0
    0.20238095236071    0.20238095236071    0.00000000000000     0
    0.19047619045714    0.19047619045714    0.00000000000000     0
    0.17857142855357    0.17857142855357    0.00000000000000     0
    0.16666666665000    0.16666666665000    0.00000000000000     0
    0.15476190474643    0.15476190474643    0.00000000000000     0
    0.14285714284286    0.14285714284286    0.00000000000000     0
    0.13095238093929    0.13095238093929    0.00000000000000     0
    0.11904761903571    0.11904761903571    0.00000000000000     0
    0.10714285713214    0.10714285713214    0.00000000000000     0
    0.09523809522857    0.09523809522857    0.00000000000000     0
    0.08333333332500    0.08333333332500    0.00000000000000     0
    0.07142857142143    0.07142857142143    0.00000000000000     0
    0.05952380951786    0.05952380951786    0.00000000000000     0
    0.04761904761429    0.04761904761429    0.00000000000000     0
    0.03571428571071    0.03571428571071    0.00000000000000     0
    0.02380952380714    0.02380952380714    0.00000000000000     0
    0.01190476190357    0.01190476190357    0.00000000000000     0
    0.00000000000000    0.00000000000000    0.00000000000000     0  Γ

![band](https://user-images.githubusercontent.com/104714131/205025484-826a611f-50bb-4fa8-a5d9-d76de55634a1.png)

**Comment by QijingZheng** [comment]
Hi

The reason is that the number of k-points between each k-path segment is not equal, whereas the script expects k-points segments with equal number of k-points.

I have modified the script, please specify the k-segment boundary by the index of the k-points with, e.g.

    pyband --nseg 0 --nseg 24 --nseg 38 --nseg 67 --hse -k gmkg

which will add vertial lines at k-points with index 1, 25, 39 and 68.

**Comment by nirjha008** [comment]
Thank you for the quick modification. 
But now, the number of vertical lines is capped at a max of 3 , If I give -k gkg instead of -k gkmg, it adds three vertical lines. Otherwise with -k gkmg, I'm getting the following error- 
>>./pyband --nseg 0  --nseg 24 --nseg 38 --nseg 67   --hse -k gkmg
Traceback (most recent call last):
  File "./pyband", line 762, in <module>
    bandplot(kpath, bands, efermi, kpt_bounds, opts, whts)
  File "./pyband", line 374, in bandplot
    ax.set_xticklabels(kpath_name_parse(opts.kpts))
  File "/cm/local/apps/python3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/cm/local/apps/python3/lib/python3.7/site-packages/matplotlib/_api/deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)
  File "/cm/local/apps/python3/lib/python3.7/site-packages/matplotlib/axis.py", line 1795, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/cm/local/apps/python3/lib/python3.7/site-packages/matplotlib/axis.py", line 1717, in set_ticklabels
    "The number of FixedLocator locations"
ValueError: The number of FixedLocator locations (3), usually from a call to set_ticks, does not match the number of ticklabels (4).

**Comment by QijingZheng** [comment]
Hi

The script works perfectly well on my computer. I noticed that line 762 of your script is different from mine, please use the latest script from my github.

**Comment by nirjha008** [comment]
Sir I updated, but the error is still present. Line 762 of pyband in my system is same as the one in github. Can you kindly check if you commit the modification, I am seeing latest commit 2 days ago on the pyband script.

**Comment by nirjha008** [comment]
Yes it works fine now. thank you very much for the fix .
