### ISSUE TITLE
An error caused by the difference between python2 and python3

### ISSUE THREAD

**Issue by IonizingRadiation** [QijingZheng/pyband#3]
Hello Mr. Zheng

I ran into an error like 
```bash
Traceback (most recent call last):
  File "../pyband", line 434, in <module>
    kpath, bands, efermi, kpt_bounds = get_bandInfo(opts.filename)
  File "../pyband", line 108, in get_bandInfo
    for ii in range(Nseg):
TypeError: 'float' object cannot be interpreted as an integer
```
when I testing `pyband` with the examples listed in this repo. 

And I guess this issue was caused by the difference of division operator `/` in py2 and py3.
The MWE below confirmed it:
```python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 3 / 2
1
```
while in python3:
```python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 3 / 2
1.5
```

So I provide a fix to it: in [this line](https://github.com/QijingZheng/pyband/blob/master/pyband#L105), substitute `/` with `//` and everything would go well (both python2 and python3 could perform `//` in same behavior.

**Comment by IonizingRadiation** [comment]
Okay, I think I can close this issue with pleasure😀

**Comment by IonizingRadiation** [comment]
Hi

The same issue occurs in `pydos` in [L46](https://github.com/QijingZheng/pyband/blob/master/pydos#L46) and [L47](https://github.com/QijingZheng/pyband/blob/master/pydos#L47), just substitute `/` with `//` and problem related to compatibility will be solved.

Best
Radiation
