### ISSUE TITLE
pyband doesn't work

### ISSUE THREAD

**Issue by deitydeng** [QijingZheng/pyband#5]
Dear Dr.Zheng
I got the following warning:
Do you have any idea for that
Thanks in advance
Traceback (most recent call last):
File "pyband", line 434, in 
kpath, bands, efermi, kpt_bounds = get_bandInfo(opts.filename)
File "pyband", line 131, in get_bandInfo
kpt_bounds = np.concatenate(([0.0,], kpt_path[np.isclose(xx, 0.0)], [kpt_path[-1],]))
IndexError: boolean index did not match indexed array along dimension 0; dimension is 16 but corresponding boolean dimension is 15

**Comment by QijingZheng** [comment]
The error complains about the k-points, there may be something wrong with
the KPOINTS file.
Here is an example KPOINTS file that I used.

Monkhorst-Pack

30

Line mod

Rec

  0.50000000000 0.00000000000 0.00000000000 # M

  0.00000000000 0.00000000000 0.00000000000 # G



  0.00000000000 0.00000000000 0.00000000000 # G

  0.33333333333 0.33333333333 0.00000000000 # K
