### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by SUN123RAY** [QijingZheng/pyband#6]
Hi Thanks for this useful script. I have tried 
python pyband.py -k mrgx
but it is showing this error message 

Traceback (most recent call last):
  File "pyband.py", line 434, in <module>
    kpath, bands, efermi, kpt_bounds = get_bandInfo(opts.filename)
  File "pyband.py", line 104, in get_bandInfo
    Nk_in_seg = int(kp[1].strip())
ValueError: invalid literal for int() with base 10: '90              ! number of k-points = 0 ->automatic generation scheme'

Can you please look on that?

**Comment by QijingZheng** [comment]
Hi

The second line of KPOINTS file should only contain the number of k-points,
no other comments are allowed.
Just remove the comments and it should be OK.

Qijing

**Comment by QijingZheng** [comment]
You numpy is too old, please upgrade to the newest version.

**Comment by SUN123RAY** [comment]
hi I have bumpy 1.11.1 and got this now
  File "pyband.py", line 452, in <module>
    call(['feh', '-xdF', opts.bandimage])
  File
"/software/apps/python/3.6.1/anaconda-4.4.0/lib/python3.6/subprocess.py",
line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File
"/software/apps/python/3.6.1/anaconda-4.4.0/lib/python3.6/subprocess.py",
line 707, in __init__
    restore_signals, start_new_session)
  File
"/software/apps/python/3.6.1/anaconda-4.4.0/lib/python3.6/subprocess.py",
line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'feh'

**Comment by SUN123RAY** [comment]
I have upgraded bumpy to latest version and tried again. It shows again
error

 Traceback (most recent call last):

  File "pyband.py", line 452, in <module>

    call(['feh', '-xdF', opts.bandimage])

  File "/Users/amiba787/anaconda/lib/python2.7/subprocess.py", line 168, in
call

    return Popen(*popenargs, **kwargs).wait()

  File "/Users/amiba787/anaconda/lib/python2.7/subprocess.py", line 390, in
__init__

    errread, errwrite)

  File "/Users/amiba787/anaconda/lib/python2.7/subprocess.py", line 1024,
in _execute_child

    raise child_exception

OSError: [Errno 2] No such file or directory
