### ISSUE TITLE
--occ not working

### ISSUE THREAD

**Issue by xlliu98** [QijingZheng/pyband#8]
Hi Qijing,
Thank you for your scripts! I am using your pyband to plot the contribution of some atoms to each KS state using " --occ" option. My command is `python pyband -k gfbg -y -2 2 --occ '123 124'`. And I got the following error :
`Traceback (most recent call last):
  File "pyband", line 429, in <module>
    lsorbit=opts.lsorbit))
  File "pyband", line 40, in WeightFromPro
    Weights.resize(nspin, nkpts, nbands, nions)
TypeError: 'float' object cannot be interpreted as an integer
` Can you look into that? Thanks!

**Comment by QijingZheng** [comment]
either use python 2.x or change the "/" in line 33 and 34 to "//".

**Comment by xlliu98** [comment]
That worked, thank you.
