### ISSUE TITLE
pyband issue

### ISSUE THREAD

**Issue by woshijamess** [QijingZheng/pyband#9]
Dear Dr. Zheng,

when I have 'pyband ' command in your example folder, the error message comes out:

Traceback (most recent call last):
  File "/data/qiangbai/bin/pyband/pyband", line 456, in <module>
    call(['feh', '-xdF', opts.bandimage])
  File "/data/qiangbai/anaconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/data/qiangbai/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/data/qiangbai/anaconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Do you know how to solve it?

Best,
Qiang

**Comment by QijingZheng** [comment]
Dear Qiang

The resulting image 'band.png' has already been generated, the script just can not find the image viewer.

Best
Qijing
